version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:14

orbs:
  puppeteer: threetreeslight/puppeteer@0.1.2

jobs:
  test:
    executor: node
    steps:
      - puppeteer/install
      - checkout

      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            - yarn-packages-

      - run: yarn install --frozen-lockfile

      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run: yarn build
      - run: yarn test -w 2

workflows:
  version: 2
  test:
    jobs:
      - test